# Generated by Django 5.1.5 on 2025-03-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='book',
            new_name='books',
        ),
    ]
